sudo: false
language: python
jobs:
  include:
    - python: "2.7"
      env: DJANGO=1.11 LINT=true
    - python: "3.6"
      env: DJANGO=1.11 LINT=true
    - python: "3.6"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=2.1
    - python: "3.6"
      env: DJANGO=2.2
    - python: "3.6"
      env: DJANGO=3.0
script:
  - "./ci.sh"
